spring.application.name=CRUD-Ope
server.port=7071

#spring.datasource.url=jdbc:mysql://localhost:3306/mydb
spring.datasource.url=jdbc:mysql://localhost:3306/mydb?createDatabaseIfNotExist=true

spring.datasource.username=root
spring.datasource.password=@Ashu2310
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
